apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-project-deploy
  labels:
    app: banking-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banking-project
  template:
    metadata:
      labels:
        app: banking-project
    spec:
      containers:
      - name: banking-project-container
        image: harishnhs/banking-project
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: banking-project-np-service
  labels:
    app: banking-project
spec:
  selector:
    app: banking-project

  type: NodePort
  ports:
  - nodePort: 31033 
    port: 8082
    targetPort: 8082
